# Generated by Django 5.0.6 on 2024-06-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='image_file/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_file/')),
                ('audio_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
